<a href="https://colab.research.google.com/github/titan-spyer/generative-ai/blob/main/CloudNotebooks/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


# Creating Tensor

In [ ]:
# Using empty
a = torch.empty(3, 2)

In [ ]:
# Check Type
type(a)

torch.Tensor

In [ ]:
# Using Zeros
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# Using ones
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
# Using rand
torch.rand(3, 2)

tensor([[0.8932, 0.7557],
        [0.6446, 0.4357],
        [0.4702, 0.2448]])

In [ ]:
# Use of seed
torch.manual_seed(50)
torch.rand(3, 2)

tensor([[0.6180, 0.0687],
        [0.3893, 0.0404],
        [0.4013, 0.1442]])

In [ ]:
# using Tensor.
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

# Tensor Shapes

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[140198606069232, 140198607926832, 140198607926960],
        [140198606179552, 140198608073584, 140198608072224]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4605, 0.4877, 0.5927],
        [0.9634, 0.1230, 0.4048]])

# Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
# Assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## Scaler Operation

In [ ]:
# Addition
x + 2
# Subtraction
x - 2
# Multipication
x * 2
# Divisin
x / 2
# int division
((x * 100)//3)%2
# Power
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

## Element wise Operation

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [ ]:
# Addition
a + b
# Subtraction
a - b
# Multipication
a * b
# Division
a / b
# Integer Division
# Power
a **b
# Mod
a %b

tensor([[0.1361, 0.0745, 0.6049],
        [0.0171, 0.0241, 0.0014]])

In [ ]:
c = torch.tensor([1, -2, -3])

In [ ]:

torch.abs(c)


tensor([1, 2, 3])

In [ ]:
torch.neg(c)

tensor([-1,  2,  3])

In [ ]:
torch.round(torch.tensor([1.2, 1.5, 1.8]))

tensor([1., 2., 2.])

## Reduction Operation

In [ ]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)

In [ ]:
# sum
torch.sum(e)
# sum along column
torch.sum(e, dim=0)
# Sum Along rows
torch.sum(e, dim=1)

tensor([18., 27.])

In [ ]:
# Mean
torch.mean(e)
# Mean along column
torch.mean(e, dim=0)
# Mean along rows
torch.mean(e, dim=1)

tensor([6., 9.])

In [ ]:
# Median
torch.median(e)
# Median along column
torch.median(e, dim=0)
# Median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([6., 9.]),
indices=tensor([0, 1]))

In [ ]:
# Max and min
torch.max(e)
torch.min(e)

tensor(4.)

In [ ]:
# Product
torch.prod(e)

tensor(139968.)

In [ ]:
# standard Deviation
torch.std(e)

tensor(2.0736)

In [ ]:
# Variance
torch.var(e)

tensor(4.3000)

In [ ]:
torch.argmax(e)

tensor(3)

In [ ]:
torch.argmin(e)

tensor(1)

### Matrix operation

In [ ]:
c= torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
d= torch.randint(size=(3, 2), low=0, high=10, dtype=torch.float32)

In [ ]:
# Matrix multipication
torch.matmul(c, d)

tensor([[68., 30.],
        [32., 19.]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# Dot Product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# Transpose
torch.transpose(c, 0, 1)

tensor([[1., 4.],
        [8., 2.],
        [3., 1.]])

In [ ]:
# Determinant
# The torch.det() function requires a square matrix (number of rows equals number of columns).
# The tensor 'e' is a 2x3 matrix, which is not square, causing the RuntimeError.
# Let's create a square matrix to demonstrate its usage.
square_matrix = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f"Square Matrix:\n{square_matrix}")
print(f"Determinant of square_matrix: {torch.det(square_matrix)}")

Square Matrix:
tensor([[1., 2.],
        [3., 4.]])
Determinant of square_matrix: -2.0


In [ ]:
torch.inverse(square_matrix)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

### Comparision Operation

In [ ]:
i = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
j = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)

In [ ]:
# Greater than
i > j
# Less Than
i < j
# Equal to
i == j
# Not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

### Special Function

In [ ]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.int16)

In [ ]:
# log
torch.log(k)

tensor([[0.6931, 0.0000, 2.0794],
        [1.0986, 0.0000, 1.7918]])

In [ ]:
torch.exp(k)

tensor([[7.3891e+00, 2.7183e+00, 2.9810e+03],
        [2.0086e+01, 2.7183e+00, 4.0343e+02]])

In [ ]:
torch.sqrt(k)

tensor([[1.4142, 1.0000, 2.8284],
        [1.7321, 1.0000, 2.4495]])

In [ ]:
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.9997],
        [0.9526, 0.7311, 0.9975]])

In [ ]:
k.to(torch.float32)

tensor([[2., 1., 8.],
        [3., 1., 6.]])

In [ ]:
torch.softmax(k.to(torch.float32), dim=0)

tensor([[0.2689, 0.5000, 0.8808],
        [0.7311, 0.5000, 0.1192]])